services:
  landing-pages:
#    build: .
    image: internetofwater/pygeoapi:latest
    user: root
    ports:
      - "5000:80"
    restart: always
    environment:
      - PYGEOAPI_URL=http://localhost:5000
    volumes:
       - ./data:/data
       - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
       - ./jsonld:/pygeoapi/pygeoapi/templates/jsonld:ro

