#
# LAST UPDATE: 2021-06-04 15:25:00-5
#=================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: localhost #change to your hostname if running your own instance
        port: 5000
    url: https://geoconnex-demo-pages.internetofwater.dev #change to host URL  if running your own instance
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: true
    language: en-US
    cors: true
    pretty_print: true
    limit: 100
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'
#    ogc_schemas_location: /opt/schemas.opengis.net
#    templates:
#      path: /skin-dashboard/templates
#      static: /skin-dashboard/static

logging:
    level: DEBUG
    # logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Demo landing pages for geoconnex.us
        description: Provides demonstration landing pages and embedded JSON-LD for individual features with hydrologic addresses. An example for participation in the geoconnex.us system.
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/internetofwater/geoconnex.us
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Team geoconnex
        url: https://github.com/internetofwater/geoconnex.us
    contact:
        address: 113 Brattle Dr
        city: Camrbidge
        stateorprovince: Massachussetts
        postalcode: 02138
        country: USA
        email: konda@lincolninst.edu
        url: https://internetofwater.org
        role: pointOfContact

resources:
    demo-gpkg:
        type: collection
        title: geoconnex landing page demo (local file)
        geojsonld: false
        description: Demonstration Geoconnex Landing Pages (from local GeoPackage data source)
        keywords:
            - monitoring location
        template: jsonld/hydrologic-location.jsonld
        links:
            - type: application/html
              rel: canonical
              title: data source
              href: https://lincolninstitute.maps.arcgis.com/sharing/rest/content/items/7b3ef4491c524bc09d1417ad0a432d92/data
              hreflang: en-US
        extents:
            spatial:
                bbox: [-170,15,-51,72]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        providers:
            - type: feature
              name: SQLiteGPKG
              data: /data/data.gpkg
              id_field: SourceID
              uri_field: uri
              table: data
    demo-esri:
        type: collection
        title: geoconnex landing page demo (web service)
        geojsonld: false
        description: Demonstration Geoconnex Landing Pages (from ESRI REST service source)
        keywords:
            - Stream Gage
        template: jsonld/hydrologic-location.jsonld
        links:
            - type: application/html
              rel: canonical
              title: data source
              href: https://services5.arcgis.com/9b85MAhVnAUWydgW/ArcGIS/rest/services/gwtc_2022_demo_data_(Feature_Service)/FeatureServer/0
              hreflang: en-US
        extents:
            spatial:
                bbox: [-170,15,-51,72]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        providers:
            - type: feature
              name: ESRI
              data: https://services5.arcgis.com/9b85MAhVnAUWydgW/ArcGIS/rest/services/gwtc_2022_demo_data_(Feature_Service)/FeatureServer/0
              id_field: SourceID
              uri_field: uri
